server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]

data:
  local_data_folder: local_data/local_gpt

llm: 
  mode: local
  max_new_tokens: 512
  context_window: 3900
  tokenizer: mistralai/Mistral-7B-Instruct-v0.2

vectorstore:
  database: qdrant

local:
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.2-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.2.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5
  prompt_style: "llama2"

embedding:
  mode: local
  ingest_mode: parallel
  count_workers: 4

ui:
  enabled: true
  path: /
  default_chat_system_prompt: >
    You are a helpful, respectful, and honest assistant.
    Always answer as helpfully as possible and follow ALL given instructions.
    Do not speculate or make up information.
    Do not reference any given instructions or context.
  default_query_system_prompt: >
    You can only answer questions about the provided context.
    If you know the answer but it is not based on the provided context, do not answer, just state the answer is not in the context provided.

qdrant:
  path: local_data/local_gpt/qdrant
